stages:
  - test

before_script:
  - apt-get update -qy

Conding Standerd Check:
  stage: test
  script:
    - apt-get install -y php php-xml
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - mv composer.phar /usr/local/bin/composer
    - composer global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
    - composer global require --dev wp-coding-standards/wpcs:"^3.0"
    - composer global require --dev phpcompatibility/phpcompatibility-wp:"*"
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - phpcs -i
    - phpcs -ps . --standard=WordPress --ignore=*/vendor/* --extensions=php

PHP Compatibility Check:
  stage: test
  script:
    - apt-get install -y php php-xml
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - mv composer.phar /usr/local/bin/composer
    - composer global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
    - composer global require --dev wp-coding-standards/wpcs:"^3.0"
    - composer global require --dev phpcompatibility/phpcompatibility-wp:"*"
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - phpcs -i
    - phpcs -p . --standard=PHPCompatibilityWP --runtime-set testVersion 7.4- --extensions=php

on:
    push:
        branches: [ "**" ]
    pull_request:
        branches: [ "**" ]
