name: PHP Code Standards and Compatibility Checks

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  coding-standards:
    name: WordPress Coding Standards
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer, phpcs

      - name: Install WPCS and PHPCompatibility
        run: |
          composer global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer global require --dev wp-coding-standards/wpcs:"^3.0"
          composer global require --dev phpcompatibility/phpcompatibility-wp:"*"
          echo "$HOME/.composer/vendor/bin" >> $GITHUB_PATH

      - name: Show installed standards
        run: phpcs -i

      - name: Run WordPress Coding Standards Check
        run: phpcs -ps . --standard=WordPress --ignore=*/vendor/* --extensions=php

  compatibility-check:
    name: PHP Compatibility Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer, phpcs

      - name: Install WPCS and PHPCompatibility
        run: |
          composer global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer global require --dev wp-coding-standards/wpcs:"^3.0"
          composer global require --dev phpcompatibility/phpcompatibility-wp:"*"
          echo "$HOME/.composer/vendor/bin" >> $GITHUB_PATH

      - name: Show installed standards
        run: phpcs -i

      - name: Run PHP Compatibility Check
        run: phpcs -p . --standard=PHPCompatibilityWP --runtime-set testVersion 7.4- --extensions=php
